### ISSUE TITLE
Provide serial numbers on RaspberryPi 4

### ISSUE THREAD

**Issue by rvs** [lf-edge/eve#1075]
On most x86 platforms EVE gets the serial number out of SMBIOS. On ARM64 (and more specifically RaspberryPi 4) the situation is more complex https://github.com/raspberrypi/linux/issues/1670

We need to settle on a way of having a serial # for our RaspberryPi 4 builds. Options I see:
   * the ones described in the issue above
   * EVE's soft-serial

Personally, I'm more inclined to do a proper SMBIOS-like solution for ARM (and avoid soft-serial) -- but even then we still need to decide how we're passing that information into the kernel (see options above).

Lets have a bit of a discussion on this ISSUE.

**Comment by rvs** [comment]
If anyone is interested in exploring a device tree overlay route -- here's the RPi's own documentation https://www.raspberrypi.org/documentation/configuration/device-tree.md

**Comment by temerkhanov** [comment]
On UEFI the SMBIOS3 tables should be published along with the other tables

**Comment by rene** [comment]
This issue can be closed, currently we are covering all the methods mentioned to get the serial from the device:

- We call dmidecode to get serial from SMBIOS, if available
- If not available, we check /proc/cpuinfo (that will contain the serial if it was specified in device tree)
- And we also consider (with the merged PR https://github.com/lf-edge/eve/pull/3024) the /sys/devices/soc0/serial_number, that comes from SoC platform driver...
