### ISSUE TITLE
CI not running on PRs

### ISSUE THREAD

**Issue by deitch** [lf-edge/eve#11]
**Description**

circleci config is in place, but CI is not running

**Steps to reproduce the issue:**

Open a PR. See no checks enabled.

**Describe the results you received:**

No CI ran.

**Describe the results you expected:**

CI runs.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by deitch** [comment]
cc @rvs

**Comment by deitch** [comment]
Update. It appears they _are_ running, but are not linked to the PRs. I opened #10 to update docs, no checks linked to required to merge, but I still received a notification email about the tests.

**Comment by rvs** [comment]
This got fixed just now
