### ISSUE TITLE
Cannot connect to VNC of VM in RPI4 (arm64) with kvm HV

### ISSUE THREAD

**Issue by giggsoff** [lf-edge/eve#1198]
# Description

I try to connect to VNC of VM created on my RPI4 with kvm HV, but my VNC client shows black screen `Guest has not initialized the display (yet) `. My VM is running and I accessible via http (it is based on linuxkit with nginx).

# Steps to Reproduce

Start VM with VNC on RPI4 with kvm HV.

# Actual Results

`Guest has not initialized the display (yet) `

# Expected Results

Access to VNC console.

**Comment by rvs** [comment]
Hey @giggsoff what's the easiest Eden command to reproduce this?

**Comment by rvs** [comment]
Hey @giggsoff -- this should be fixed in this nightly snapshot

**Comment by giggsoff** [comment]
Hi @rvs! Your update works for me. Thank you!
