### ISSUE TITLE
Cannot start VM with userData on RPI4 (arm64) with kvm HV.

### ISSUE THREAD

**Issue by giggsoff** [lf-edge/eve#1199]
# Description

I try to start VM with userData on RPI4 (arm64) with kvm HV. But it moves into HALTED state.

# Steps to Reproduce

Start VM with userData on RPI4 (arm64) with kvm HV.

# Actual Results

VM is not RUNNING (HALTED).

# Expected Results

VM is RUNNING.

# Additional Information

In syslog I see error `qemu-system-aarch64:/var/run/domainmgr/xen/xen1.cfg:110: Bus 'ide.0' not found`

**Comment by rvs** [comment]
Hey @giggsoff what's the easiest Eden command to reproduce this? (maybe we should include this question into the template)

**Comment by rvs** [comment]
Hey @giggsoff -- this should be fixed in this nightly snapshot

**Comment by giggsoff** [comment]
Hi @rvs! Your update works for me. Thank you!
