### ISSUE TITLE
Refactor running unit tests

### ISSUE THREAD

**Issue by rvs** [lf-edge/eve#121]
Unit tests need to be put into a separate check in the circle pipeline and we also need to make sure make test target returns non-0 exit code if tests fail

**Comment by dave-tucker** [comment]
It looks like this is already the case so this issue might be able to be closed.
For example, on #391, the `test` job == unit tests.
![image](https://user-images.githubusercontent.com/3781777/68997738-7f7ee180-08a1-11ea-95df-013748265df1.png)

**Comment by dave-tucker** [comment]
I've also verified that the exit code does indeed propagate correctly, although there is no feedback as to which test failed without reading the Junit report. I'll open an (optional) PR to address that but based on the description of the issue I think this can be closed.

**Comment by milan-zededa** [comment]
Done by @dave-tucker
