### ISSUE TITLE
Cannot connect to VNC on RPi4 (arm64) with xen hypervisor.

### ISSUE THREAD

**Issue by giggsoff** [lf-edge/eve#1216]
# Description

I try to start APP on my RPi4 with xen hypervisor, and it starts fine. But I cannot connect to VNC console of deployed VM.

# Steps to Reproduce

With [EDEN](https://github.com/lf-edge/eden) you can try:
_Note: at the moment you need to manually build eserver: `docker build eserver lfedge/eden-http-server:latest`_

1. `make CONFIG='--devmodel RPi4' build`
2. `./eden config set default --key eve.hv --value xen`
3. `./eden config set default --key eve.tag --value 0.0.0-snapshot-master-f8ba508e`
4. `./eden setup`
5. Transfer image (from last line of output) into SD and boot RPi4
6. `./eden start`
7. `./eden eve onboard`
8. `./eden test tests/vnc -v debug -r TestVNCVMStart`

# Actual Results

Test failed with timeout.

# Expected Results

VNC connection to port 5901 of RPI.

# Additional Information

In xen config, I see
```
(ns: pillar) bc172e66-e5f6-4e68-89b6-31250b6e1ba0:/# grep vnc /var/run/domainmgr
/xen/xen1.cfg
vnc = 1
vnclisten = "0.0.0.0"
vncdisplay = 1
```

**Comment by rvs** [comment]
Hey @giggsoff -- as we've talked about I'd recommend experimenting with https://xenbits.xen.org/docs/unstable/man/xl.cfg.5.html#Emulated-VGA-Graphics-Device and if that doesn't result in anything -- we may need to hack https://github.com/xen-project/xen/tree/master/tools/libxl
