### ISSUE TITLE
Eve 5.8.2 doesn't reboot after onboarding

### ISSUE THREAD

**Issue by mydatascience** [lf-edge/eve#1278]
# Description

Eve doesn't reboot after onboarding. Using Adam and Eden 

# Steps to Reproduce

for Eden: 

make build
./eden config add default
./eden config set default --key=eve.tag --value=5.8.2
./eden test ./tests/workflow

# Actual Results

Eden onboard (3/11)
time="2020-08-07T09:33:50Z" level=info msg="testData directory: testdata"
edenProg: /var/lib/jenkins/workspace/eve-docker-image/dist/bin/eden timewait: 0s
testProg: /var/lib/jenkins/workspace/eve-docker-image/dist/bin/eden.reboot.test timewait: 0s
--- FAIL: TestEdenScripts (0.00s)
    --- FAIL: TestEdenScripts/eden_onboard (1945.11s)
        testscript.go:392: 
            # eden start
            # Onboarding. (120.077s)
            # Waiting of onboard reboot. (1825.034s)
            > test eden.reboot.test -test.v -timewait 1800 -reboot=0 -count=1 &
            testProg: /var/lib/jenkins/workspace/eve-docker-image/dist/bin/eden.reboot.test
            > wait
            [background] eden.reboot.test -test.v -timewait 1800 -reboot=0 -count=1 &: exit status 1
            [stdout]
            Reboot Test
            === RUN   TestReboot
            --- FAIL: TestReboot (1825.00s)
                reboot_test.go:123: Wait for state of node1
                reboot_test.go:125: timewait:  1800
                reboot_test.go:126: reboot:  false
                reboot_test.go:127: count:  1
                testContext.go:295: done waiting for state
                reboot_test.go:133: lastRebootTime: 2020-08-07T09:34:59.854227388Z
                reboot_test.go:146: Wait for reboot of node1
                testContext.go:226: WaitForProc terminated by timeout 30m0s
                reboot_test.go:153: Reboot number: 1
                reboot_test.go:156: Number of reboots: 1
            FAIL
            [stderr]
            time="2020-08-07T09:35:50Z" level=info msg="config updated /var/lib/jenkins/.eden/devUUID-95ff4233-6a25-4821-9cf8-783ebc805164.json"
            time="2020-08-07T09:35:50Z" level=info msg="state updated /var/lib/jenkins/.eden/state-2b00c73f-adac-435d-a8bb-05a54db02d0c.yml"
            FAIL: testdata/eden_onboard.txt:9: unexpected command failure

# Expected Results

Test passed

# Additional Information

Eve onboards, but doesn't reboot. Likely to be valid for Adam and v1 API

**Comment by eriknordmark** [comment]
@mydatascience Please point me at the adam documentation for how to specify how to run eden with the EVE image I just built on my laptop. Note that I have no desire to tag the image and upload it. I tried manually copying it from my eve workspace to dist/images/eve/live.img but that doesn't work.

**Comment by eriknordmark** [comment]
Note that I can cobble things together so that eden eve start picks up the live.img etc from my EVE workspace, but the tests don't work in that setup. Fails with
            FAIL: testdata/eden_setup.txt:4: no match for `download EVE done:` found in stdout
So there seems to be an invalid assumption that the tests should always download even when download is set to false in the config file.

**Comment by mydatascience** [comment]
You may remove  or comment ( # ) line 2 and 3  so it will not execute setup and go to start or even start eden and comment out start test as well (lines 4 and 5)
 this file  (./tests/workflow/eden.workflow.tests.txt) 
https://github.com/lf-edge/eden/blob/master/tests/workflow/eden.workflow.tests.txt
