### ISSUE TITLE
Save TPM2.0 Model + Firmware information in a file in  /persist/config

### ISSUE THREAD

**Issue by cshari-zededa** [lf-edge/eve#1430]
This will be useful when the device is in a problem state (not accessible any more, especially in headless systems), where with a troubleshooting usb stick, we can retrieve this information along with other pieces of info taken with PR#1427

**Comment by eriknordmark** [comment]
Can this be closed by #1427?

**Comment by cshari-zededa** [comment]
> Can this be closed by #1427?

Yes it can be closed. Closing
