### ISSUE TITLE
Missing docker image in RPi4 build

### ISSUE THREAD

**Issue by flounderfish** [lf-edge/eve#1600]
# Description

I am unable to execute `make` per the documentation [here](https://github.com/lf-edge/eve/blob/master/README.md#how-to-write-eve-image-and-installer-onto-an-sd-card-or-an-installer-medium) on writing an EVE image to an sd card for a Raspberry Pi 4 build; the process fails consistently and repeatedly:

`Failed to build init tarball from lfedge/eve-dom0-ztools:8cf6bb2af80e202f636ffe4a11c22b151ac572af-arm64: Could not pull image lfedge/eve-dom0-ztools:8cf6bb2af80e202f636ffe4a11c22b151ac572af-arm64: Error response from daemon: manifest for lfedge/eve-dom0-ztools:8cf6bb2af80e202f636ffe4a11c22b151ac572af-arm64 not found: manifest unknown: manifest unknown`

# Steps to Reproduce

After following the above generic build instructions, execute `make ZARCH=arm64 HV=rpi live-raw`

# Actual Results

The docker image is not found (see exact error message in description)

# Expected Results

The docker should pull, the build should be on its merry way so that I can flash it to disk. Or, if this is not yet ready for rpi4, the documentation should reflect that

# Additional Information

I checked Docker Hub, and while there are `amd64` images for `8cf6bb2af80e202f636ffe4a11c22b151ac572af`, there are none for `arm64`. I am willing to attempt a workaround, such as another place where I can grab the image, or perhaps even building that specific docker image myself, provided you can point me towards some detailed instructions (this is my first go with the EVE project)

**Comment by rvs** [comment]
Hey @flounderfish -- thanks for reporting it. Sadly our CI/CD server for ARM broke. We're currently trying to see whether we can leverage any publicly available CI/CD system that provides ARM slaves for builds. No luck so far. Please bear with us while we're going through this transition (and if you have suggestions for where we can find free CI/CD system for ARM -- please let us know ASAP).

**Comment by rvs** [comment]
By the way @flounderfish -- we're still managing to publish official releases for ARM (by basically personally paying for a AWS ARM instance) so you can at least do:
```
git clone https://github.com/lf-edge/eve.git
cd eve
git checkout 5.15.0
make ...
```

This way you'll be getting 5.15.0 release artifacts (instead of latest master ones)

**Comment by rene** [comment]
Closing since this issue is deprecated, currently we don't have any issues to generate RPi images.
