### ISSUE TITLE
Applications hang in CREATING_VOLUME state

### ISSUE THREAD

**Issue by giggsoff** [lf-edge/eve#1614]
# Steps to Reproduce

New tests in the Eden side fails from time to time.

# Actual Results

Applications are moved to the `CREATING_VOLUME` state and remain there.

```
jenkins@jenkins-eden:~/workspace/Eden-dailyto/eden$ ./eden pod ps
NAME    IMAGE                   UUID                                    INTERNAL        EXTERNAL                STATE(ADAM)     LAST_STATE(EVE)
ping-fw itmoeve/eclient:latest  a2c2ee07-7a82-41e5-aba5-903138481f35    -:22            10.138.15.235:2224      IN_CONFIG       CREATING_VOLUME
ping-nw itmoeve/eclient:latest  9bf0625a-1e00-49dd-bfd9-85c408dff4aa    10.1.0.2:22     10.138.15.235:2223      IN_CONFIG       RUNNING
pong    itmoeve/eclient:latest  f4a481e0-d27a-4117-adf9-0b3a04df74d3    -               -                       IN_CONFIG       CREATING_VOLUME
```

# Expected Results

`RUNNING` state

# Additional Information

My syslog in the attachment (here is the series of tests)
[syslog_stuck_apps.txt](https://github.com/lf-edge/eve/files/5494659/syslog_stuck_apps.txt)

**Comment by giggsoff** [comment]
It may have the same source as my previous problem #1602 . Seems, that we have some broken state passed into `doUpdateVol` or we not fire it again to move the state.

**Comment by giggsoff** [comment]
In Eden, we merge contentInfo for the same docker images. Zedcloud split them into different ones. I'll try the official configuration option.

**Comment by eriknordmark** [comment]
Do you have some more details on what you expect other than RUNNING state?

**Comment by eriknordmark** [comment]
From the syslog file I see app_instance_status-9bf0625a-1e00-49dd-bfd9-85c408dff4aa move to CREATED_VOLUME.

**Comment by eriknordmark** [comment]
Taken care of by #1670
