### ISSUE TITLE
Ubuntu VMs are apparently not starting on EVE master

### ISSUE THREAD

**Issue by temerkhanov** [lf-edge/eve#1864]
There seems to be an issue with Ubuntu VMs when they get stalled at some point on the current master. Log messages are empty.

**Comment by rvs** [comment]
Without more details this is next to impossible to investigate. Please provide some @temerkhanov or close the issue if details are hard to come by.

**Comment by lucianoctorres** [comment]
We are having an issue which could be related.

We have an image using Ubuntu 18 deployed on Eve. In our devices fleet, every other day one of them just hangs. Upon reboot, there is nothing special in syslog or kernel log, it just stops.

@temerkhanov  is that what you are seeing?

**Comment by temerkhanov** [comment]
The issue I saw was Ubuntu 20.04 simply not starting on the Supermicro platform in the VMs without any output at all
