### ISSUE TITLE
make run with CONF_PART fails to boot

### ISSUE THREAD

**Issue by danielrs** [lf-edge/eve#1886]
I was trying to run Eve in QEMU against a local Adam server. However, when I run `make run CONF_PART="$(PWD)/../adam/run/config"` I get the following error:

```
BdsDxe: failed to load Boot0001 "UEFI QEMU DVD-ROM QM00005 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x2,0xFFFF,0x0): Not Found
BdsDxe: failed to load Boot0002 "UEFI QEMU HARDDISK QM00001 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x0,0xFFFF,0x0): Not Found
>>Start PXE over IPv4.
```
Tried to wait but it eventually takes me to the rescue shell.

### Set up and run Adam

1. `git clone https://github.com/lf-edge/adam`
2. `cd adam`
3. `go build`
4. `./adam generate --cn 10.10.20.171 --hosts 10.10.20.171`
5. `./adam server`

### Set up and run Eve

1. `git clone https://github.com/lf-edge/eve`
2. `cd eve`
3. `make build-tools`
4. `make live`
5. `make run`
6. `make run CONF_PART="$PWD/../adam/run/config"`

## Actual Results

Failed to boot.

## Expected Results

Should have booted.

## Additional Information

Booting without `CONF_PART` works fine.

QEMU version:

```
QEMU emulator version 4.2.1 (Debian 1:4.2-3ubuntu6.11)Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers
```

**Comment by rvs** [comment]
Hey @danielrs -- I think you're taking these steps from Adam documentation -- we need to updated that. In fact, we've moved away from using standalone Adam (aside from pure developer-focused scenarios) towards using a more user-friendly orchestration that we've done in Eden: https://github.com/lf-edge/eden#quickstart

I highly recommend you give that a try.

And yes @deitch and I need to update Adam docs.

**Comment by danielrs** [comment]
Thanks I was able to get Eve and Adam running together following the Quickstart you linked.

I don't know if this is the right place to ask (it would be more appropriate at Eden issues), but is it possible to run a Docker container with custom flags? Or maybe a way to override the container default environment variables or config?

For example, I would like to do something like:

```
eden pod deploy -p 8028:80 docker://myapp -- --myapp-arg 0 --myapp-flag
```

**Comment by giggsoff** [comment]
Hi, @danielrs. Sorry for the late answer.
You can use such way for setting environments (separated by `\n`):
```
eden pod deploy -p 8028:80 docker://myapp --metadata='myapp-arg=0\nmyapp-flag=true'
```

**Comment by sgdelleng** [comment]
Hi
The Eden mechanism is fantastic and is great for trying things out.
However we would really like to follow up on what @danielrs was trying to do with standalone Adam and Eve setups
The ability to run Eve in qemu is perfect in many situations and we would appreciate some help in getting the CONF_PART feature to work
Are you saying that this is completely off the table now?

**Comment by sgdelleng** [comment]
> 
> 
> Hey @danielrs -- I think you're taking these steps from Adam documentation -- we need to updated that. In fact, we've moved away from using standalone Adam (aside from pure developer-focused scenarios) towards using a more user-friendly orchestration that we've done in Eden: https://github.com/lf-edge/eden#quickstart
> 
> I highly recommend you give that a try.
> 
> And yes @deitch and I need to update Adam docs.

Actually the CONF_PART option is relevant to Eve I believe - not to Adam. 
Configuration generated by Adam is being used to feed into Eve but its the ability to run on QEMU with the configuration mounted from a folder is what is attractive about the feature. 
It would allow us to quickly change configuration to test things 

> qemu-system-x86_64 -smbios type=1,serial=31415926 -m 4096 -smp 4 -display none -drive if=pflash,format=raw,unit=0,readonly,file=/home/saycat/eve/dist/amd64/current/installer/firmware/OVMF_CODE.fd -drive if=pflash,format=raw,unit=1,file=/home/saycat/eve/dist/amd64/current/installer/firmware/OVMF_VARS.fd -serial mon:stdio -rtc base=utc,clock=rt -netdev user,id=eth0,net=192.168.1.0/24,dhcpstart=192.168.1.10,hostfwd=tcp::2222-:22 -device virtio-net-pci,netdev=eth0,romfile="" -netdev user,id=eth1,net=192.168.2.0/24,dhcpstart=192.168.2.10 -device virtio-net-pci,netdev=eth1,romfile="" -machine q35 -cpu SandyBridge  -drive file=fat:rw:conf/,format=raw -drive file=/home/saycat/eve/dist/amd64/current/live.qcow2,format=qcow2
vvfat conf/ chs 1024,16,63
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.x2apic [bit 21]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.tsc-deadline [bit 24]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.avx [bit 28]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.x2apic [bit 21]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.tsc-deadline [bit 24]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.avx [bit 28]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.x2apic [bit 21]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.tsc-deadline [bit 24]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.avx [bit 28]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.x2apic [bit 21]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.tsc-deadline [bit 24]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.avx [bit 28]
BdsDxe: failed to load Boot0001 "UEFI QEMU DVD-ROM QM00005 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x2,0xFFFF,0x0): Not Found
BdsDxe: failed to load Boot0002 "UEFI QEMU HARDDISK QM00001 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x0,0xFFFF,0x0): Not Found

**Comment by rvs** [comment]
Hey @danielrs -- given @giggsoff comments, can we close this now?

**Comment by danielrs** [comment]
@rvs Thanks for the help, I was able to make it boot!
