### ISSUE TITLE
install EVE-OS on RPi4 using USB memory stick installer approach fails

### ISSUE THREAD

**Issue by kgiori** [lf-edge/eve#2114]
Goal was to install EVE-OS onto an RPi using the standard USB stick installation method (used to install EVE-OS on x86 hardware)

The approach:
* Update RPi4 bootloader to the latest version and configure the RPi to boot from a USB memory stick
* Prepare a blank micro SD card to insert into the RPi
* Prepare a USB memory stick with the EVE-OS installer image
* Boot the RPi with the blank micro SD card and the prepared USB memory stick

# BUG REPORT INFORMATION

# Description

Using standard EVE-OS installation approach (by booting hw from USB stick with EVE-OS installer app) does not seem to work for the RPi4

# Steps to Reproduce

I used [this](https://www.raspberrypi.org/documentation/hardware/raspberrypi/booteeprom.md#imager) approach to update the bootloader and config to boot from USB then SD.

Update of RPi bootloader and boot from USB first seemed to work. On the console I saw:
```SIG vl805.sig 6246230ecd5b472902e6a49c95e857a5e3190c4fa6c462d6a8867e9a5e523a7c 0
Read vl805.bin bytes    99224 hnd 0x000000ed
PCI reset
PCI reset
VL805 EEPROM: 74606 diffs
Updating VL805
Verify VL805 EEPROM
SIG pieeprom.sig 1ebca12b90c23fcddfb7b3188e9f4f6807756df64a99b0a2bf584057faa5b222 0
Read pieeprom.bin bytes   524288 hnd 0x0000009f
Reading EEPROM: 524288
Writing EEPROM
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++.............................................+
Verify BOOT EEPROM
Reading EEPROM: 524288
BOOT-EEPROM: UPDATED
```

And the HDMI screen was all green, the indicator of success.

# Actual Results

But when I inserted a blank microSD card and the EVE-OS installer image, I saw the following as the HDMI screen output:
![IMG_4865](https://user-images.githubusercontent.com/9487286/120415335-38840000-c310-11eb-82d1-256b2af39d17.jpg)

# Expected Results

I had expected to watch the installer create an EVE-OS image on the microSD card volume. The screen shows that a card was detected.

# Additional Information

I used the following commands (on my MacOS laptop) to write 0s to the SD card to ensure that it was blank.
```$ diskutil umountDisk disk3
$ sudo dd if=/dev/zero of=/dev/rdisk3 bs=1m count=10
$ diskutil eject disk3
```

I used the following command (on my MacOS laptop) to create the USB installer image
`docker run lfedge/eve:latest -f raw installer_raw > installer.raw`

**Comment by Insei** [comment]
Hello!
1) I fix problems with rpi4 in my PR. (we have to wait for it to be accepted)
2) You need add a **-arm64** to eve tag in your command for creating usb installer for rpi4, as example:
`docker run lfedge/eve:latest-arm64 -f raw installer_raw > installer.raw`

**Comment by kgiori** [comment]
Great! And yes, with respect to adding -arm64 to the docker run command, I noted that error myself after the fact. I'm ready with the correct arch installer image for my next try. :)

**Comment by kgiori** [comment]
Has this problem been fixed and merged into the docker image? I just tried running `eve:latest-arm64` but I see the same error.

**Comment by kgiori** [comment]
Sorry! I pulled the latest and it seems to be working!

**Comment by kgiori** [comment]
But now I have run into this new problem. Where the USB installer can't seem to find/mount the blank microSD card.
![IMG_4905](https://user-images.githubusercontent.com/9487286/122126782-18137580-cde7-11eb-9cf0-14769aacb1ab.jpg)

**Comment by Insei** [comment]
it looks like you don't have enough power for the rpi 4 to initialize your USB stick.

**Comment by kgiori** [comment]
> it looks like you don't have enough power for the rpi 4 to initialize your USB stick.

I'm guessing the text shown in the screenshot is being generated by a bootloader running on board, and not (my mistake) of the USB stick installer failing to mount the blank microSD card. You can see if identify a SDHC card but because it is blank, it can't mount it. 

What clue makes you think the board does not have enough power? I'm using a standard RPi4 power dongle -- 5.1V 3A. Unfortunately all my other old power supplies with more power are not USB-C.

Maybe I should try another USB stick, with a standard RPi boot image. If it can boot from that, it seems power wouldn't be the issue?

**Comment by Insei** [comment]
I just read the log, "Attempt to find and mount boot media". I have not encountered this problem. I think formatting sdcard in fat32 can help you.

**Comment by kgiori** [comment]
Have you successfully done this USB-installer / blank SD target approach to write eve-os onto an RPi4? or know anyone who has done it? I tried a FAT32 formatted SD card and an SD card that had Raspbian already (with plenty of extra space), but both show the exact same errors. After watching the installation log screen in more detail, it does appear that the "boot from USB stick installer" aspect is working. But mounting the SD card in order to write to it seems to be failing.

**Comment by Insei** [comment]
My installation with usb was working at the time I made a PR for its fix. 

I will test it again, but a little later, right now, tests are running on my rpi4, and after them, I will deal with your problem.

**Comment by Insei** [comment]
@kgiori  The situation is that the problem is only on the Rpi4 with 8GB of RAM. Until now, I only had rpi4 with 4GB of memory and could not test it on rpi 4 with 8GB of ram. It seems that the USB driver in the kernel does not work on rpi4 with 8GB of RAM, but in rpi4 with 4GB all works well. I will try to fix it.

**Comment by Insei** [comment]
Fixed, we are waiting for when the PR is accepted.

**Comment by Avinashpatil0609** [comment]
Hello, 
I have followed instructions given above but my installation. but the installation got stuck in between, please refer the attached screenshot for reference.
Any suggestions would be really appreciated.
![Image from iOS](https://user-images.githubusercontent.com/63602119/131337781-9d73471e-3823-4421-93bc-6145656931e6.jpg)

Thanks & regards,
Avinash

**Comment by Insei** [comment]
@Avinashpatil0609 The installer says it cannot find a free disk to install. make sure the SD card is inserted into the RPi4 and formatted. Formatting is best done using the [Raspberry Pi Imager app](https://www.raspberrypi.org/software/).

**Comment by Avinashpatil0609** [comment]
@Insei , Thank you. It's working now. Is below expected output?
![Image from iOS (1)](https://user-images.githubusercontent.com/63602119/131345533-acacceb5-4902-4c16-86ad-15ed9149f7ab.jpg)

**Comment by ashwinsekaran** [comment]
Hi Team, i did the same way how Avinash did above but getting different error as attached. please let me know what went wrong over here?

![WhatsApp Image 2021-08-30 at 7 02 27 PM](https://user-images.githubusercontent.com/63737992/131347309-08611aa0-7207-41e8-969e-5c9a68276734.jpeg)

**Comment by Insei** [comment]
@Avinashpatil0609 yup, this is normal.

@ashwinsekaran What's your rpi4 model with 8GB RAM? and which version of EVE are you installing? And make sure you connect a sufficiently powerful and high quality power supply for the rpi4.
