### ISSUE TITLE
Add support for Intel PTT & AMD fTPM in addition to TPM 2.0

### ISSUE THREAD

**Issue by floucks** [lf-edge/eve#2203]
Please enable the use of PTT & fTPM in place of TPM 2.0. 

There are many constrained edge systems such as gateways that don't support TPM 2.0, but can make use of Intel PTT or AMD's fTPM. Enabling the use of these trust platforms would dramatically broaden available secure hardware options.

A great example of hardware that would work wonderfully are most of the devices in [OnLogic's portfolio.](https://www.onlogic.com/)

**Comment by rvs** [comment]
Hey @floucks -- while I would agree that adding fTPM support *in addition* to TPM 2.0 may be useful -- surely it won't be *instead of*.

Now, as a matter of personal preference I don't think fTPM are trustworthy enough, but that's neither here nor there.

Back to the matter at hand: I think that most modern fTPMs actually support 2.0 which means they should just work out of the box on EVE (do you see evidence to the contrary?).

Also summoning @eriknordmark for more aircover ;-)

**Comment by floucks** [comment]
Hi @rvs!!
I'm a commercial customer of Zededa so let's start with that...my understanding from the team is PTT "won't work" (not here for commercial support, but trying to get the ball rolling upstream if there is indeed a ball to roll). 

I'd like to stage a test and try it out but I'm pretty new to contributing on this project (though I've been following it for some time) so it might take me some time. I can get my hands on a device supporting PTT or other fTPM that is 2.0 compatible and load EVE. 

Main use case is for a device like this https://www.onlogic.com/cl210g-11/

**Comment by rvs** [comment]
Honestly, I haven't really worked much with fTPMs since I think they are mostly 1.2. However, I've seen at least AMD ones claim 2.0 APIs. But again -- haven't had hands-on experience with those.

The only OnLogic device I have in my lab is Karbon-300 and that one actually comes with a Nuvoton (just checked).

So... yes... I'd love to work with you on the device that has a 2.0 compatible fTPM -- just to see what happens. Do you think you can put it in a DMZ someplace so we both have access to it?

**Comment by eriknordmark** [comment]
I've seen laptop with TPM 2.0 fTPM, but I haven't see it anywhere else. But AFAIK they implement the TPM 2.0 specification so EVE shouldn't need to do anything special.

**Comment by floucks** [comment]
@rvs & @eriknordmark Thank you for the responses.
I'll get a demo unit using Intel PTT...should arrive in the next 2 weeks. Once I have it online I'll load EVE...but I may need some support with a controller to connect it to...happy to connect it to my Zededa tenant but I'll need a device template to do so. If anyone can help walk me through making one I'm happy to do the leg work. Regarding providing access, @rvs I can enable ZTNA access to you through our Netfoundry tenant. I can email you the specifics...just a desktop client and an enrollment token and you'll have access.

**Comment by rvs** [comment]
Hey @floucks 

> I'll get a demo unit using Intel PTT...should arrive in the next 2 weeks. Once I have it online I'll load EVE...but I may need some support with a controller to connect it to...happy to connect it to my Zededa tenant but I'll need a device template to do so. 

You can actually generate the vanilla template yourself. This doc can be helpful https://github.com/lf-edge/eve/blob/master/docs/HARDWARE-MODEL.md once you have that you can either send it to me or use zcli to register it with your enterprise.

> Regarding providing access, @rvs I can enable ZTNA access to you through our Netfoundry tenant. I can email you the specifics...just a desktop client and an enrollment token and you'll have access.

That may be quicker than following doc above -- if that's not too much trouble for you -- you can email me at roman at zededa dot com

**Comment by floucks** [comment]
@rvs Fantastic! Let me get the unit here, then I'll take a closer look and make a call. The unit has shipped and is due to arrive Monday the 9th. I'll reach back out then!

**Comment by floucks** [comment]
@rvs I've sent you an access invite. I have the latest version of eve installed on the endpoint and it loaded fine and is connected to the zedcloud controller AFAIK. If you can generate the model template or help me perform the next steps I'm happy to assist wherever I can. Perhaps I need to install a debug version of EVE onto the endpoint?

**Comment by floucks** [comment]
@rvs @eriknordmark Ok! So we've onboarded the CL210G-11-RS unit from OnLogic via ([Eden PR 665](https://github.com/lf-edge/eden/pull/665). Enabling fTPM in the OnLogic UEFI menus worked perfectly and pretty seamlessly. Nice job team!

Following up to this, I tried onboarding an Intel NUC yesterday which also uses PTT. In the BIOS we ensured UEFI & secure boot was enabled, and that legacy boot mode was disabled. Intel PTT is enabled as well. However Eve/ZedControl does not recognize the HSM. Model NUC5i7RYH. Any ideas as to why? Any debugging commands I can run (or I can delegate access to the onboarded unit as well). Thanks team!

**Comment by rvs** [comment]
> Any ideas as to why?

I can bet $5 this is b/c that TPM gets advertised as 1.2

As I mentioned before -- not much we can do here.

**Comment by floucks** [comment]
Makes sense...any way you can think of for me to test the theory on my end through the debug console? PTT "should" advertise as 2.0 and I can work on that with Intel as time goes on, looking for a way to confirm the suspicion. Either way, we can close this Issue.

**Comment by rvs** [comment]
dmsg should have some information about how it is seen

**Comment by floucks** [comment]
Thanks @rvs, I'll get into it.

**Comment by floucks** [comment]
FYI I've been running a device with Intel PTT for some time now. While I haven't gotten around to running dmsg on it yet, EVE seems content with PTT as long as it presents as TPM 2.0. Thanks!
