### ISSUE TITLE
How to run VMs inside EVE?

### ISSUE THREAD

**Issue by YustasSwamp** [lf-edge/eve#2893]
I've deployed EVE OS from the ISO image (generated by `docker run lfedge/eve:8.11.0-kvm-amd64 installer_iso > eve-iso.img`)
But I didn't find any documentation how to install KVM/QEMU hypervisor there and how to run my Linux VM there.
Is it supported option?

**Comment by mikem-zed** [comment]
> I've deployed EVE OS from the ISO image (generated by `docker run lfedge/eve:8.11.0-kvm-amd64 installer_iso > eve-iso.img`) But I didn't find any documentation how to install KVM/QEMU hypervisor there and how to run my Linux VM there. Is it supported option?

EVE by itself do not have any tools to deploy VMs or containers. It needs a 'controller' to operate. User sends commands to controller and then EVE talks to controller and get its current config e.g. "new application appeared, install it form here". Open source controlled for EVE is called Adam. To communicate with Adam Ededn tool is used. Look into corresponding repositorie's readme file https://github.com/lf-edge/eden

**Comment by kgiori** [comment]
On Tue, Nov 15, 2022 at 7:29 PM mikem-zed ***@***.***> wrote:

> I've deployed EVE OS from the ISO image (generated by docker run
> lfedge/eve:8.11.0-kvm-amd64 installer_iso > eve-iso.img) But I didn't
> find any documentation how to install KVM/QEMU hypervisor there and how to
> run my Linux VM there. Is it supported option?
>
> EVE by itself do not have any tools to deploy VMs or containers. It needs
> a 'controller' to operate. User sends commands to controller and then EVE
> talks to controller and get its current config e.g. "new application
> appeared, install it form here". Open source controlled for EVE is called
> Adam. To communicate with Adam Ededn tool is used. Look into corresponding
> repositorie's readme file https://github.com/lf-edge/eden
>
There is also a free developer trial for a commercial controller that you
can use from ZEDEDA, to manage your EVE edge nodes. You just need to sign up
<https://zededa.com/welcome-to-the-zededa-developer-program/>.
