### ISSUE TITLE
Edge application running on top of "switch" network instance FAILED createACL

### ISSUE THREAD

**Issue by FendriFiras** [lf-edge/eve#2934]
#### Error Description

I am trying to deploy any edge application (container, Virtual Machine) and attach it to a "switch network" instance and get the ip of the application.

####  How to reproduce
* Eden version [] 
* EVE-OS version  [9.0] (tested with older version like 6.0.0 and same error)
* EVE-OS hardware architecture [amd64]
The normal workflow of configuring Eden with local env 

`make clean`
`make build-tests`
`eden setup `
`source ~/.eden/activate.sh `
`eden start`
`eden start`
`eden eve onboard `

> ✔ Adam status: container with name eden_adam is running
	Adam is expected at https://192.168.100.4:3333
	For local Adam you can run 'docker logs eden_adam' to see logs
✔ Registry status: container with name eden_registry is running
	Registry is expected at https://192.168.100.4:5050
	For local registry you can run 'docker logs eden_registry' to see logs
✔ Redis status: container with name eden_redis is running
	Redis is expected at 192.168.100.4:6379
	For local Redis you can run 'docker logs eden_redis' to see logs
✔ EServer process status: container with name eden_eserver is running
	EServer is expected at http://192.168.100.4:8888 from EVE
	For local EServer you can run 'docker logs eden_eserver' to see log
✔ EVE REMOTE IPs: 192.168.0.10; fe80::7f72:e756:6d1e:75dd; 192.168.0.11; fe80::a7e4:cdde:5b5d:a290
	Last info received time: 2022-11-18 11:47:53 +0100 CET
✔ EVE memory: 0 B/0 B
✔ EVE on Qemu status: running with pid 642723
	Logs for local EVE at: /home/firas/Desktop/PFE/Project/EVE-EDEN-ADAM/eden1/dist/default-eve.log
✔ EVE Request IP: 192.168.100.4

Creating and deploying a "switch network instance" with eden
`eden network create --type switch -n direct`

>eden network ls                             
NAME	UUID					TYPE		CIDR	STATS	STATE(ADAM)	LAST_STATE(EVE)
direct	b9f051a1-df7a-4eb8-9c70-c9452e447de1	ZnetInstSwitch		-	IN_CONFIG	ACTIVATED

Deploying nginx application and attach to the created network
`eden pod deploy -p 8028:80 --networks direct docker://nginx `

error occurs❌

#### Error message

Last State:

> INSTALLED: [description:"createACL: PortMap without appIP for lport 8028/protocol tcp: {Matches:[{Type:protocol Value:tcp} {Type:lport Value:8028}] Actions:[{Drop:false Limit:false LimitRate:0 LimitUnit: LimitBurst:0 PortMap:true TargetPort:80}] Name: RuleID:2 Dir:0}\n\n"  timestamp:{seconds:1668768969  nanos:34538877}  severity:SEVERITY_ERROR]

#### Configuration of EVE
```{
    "id": {
        "uuid": "d0a1cbb0-2368-474a-a3c1-0c0ab6abbb44",
        "version": "6"
    },
    "apps": [
        {
            "uuidandversion": {
                "uuid": "6369e1b2-a1bf-4813-917b-25357d3e73ca",
                "version": "1"
            },
            "displayname": "affectionate_wiles",
            "fixedresources": {
                "memory": 1000000,
                "maxmem": 1000000,
                "vcpus": 1,
                "virtualizationMode": 1
            },
            "drives": [
                {
                    "image": {
                        "uuidandversion": {
                            "uuid": "c93663f5-62d7-4538-b79d-e45332300a6d",
                            "version": "1"
                        },
                        "name": "library/nginx:latest",
                        "iformat": 8,
                        "dsId": "7e762016-3838-4129-8516-185e2fdc44cc"
                    }
                }
            ],
            "activate": true,
            "interfaces": [
                {
                    "name": "default",
                    "networkId": "b9f051a1-df7a-4eb8-9c70-c9452e447de1",
                    "acls": [
                        {
                            "matches": [
                                {
                                    "type": "ip",
                                    "value": "0.0.0.0/0"
                                }
                            ],
                            "id": 1
                        },
                        {
                            "matches": [
                                {
                                    "type": "protocol",
                                    "value": "tcp"
                                },
                                {
                                    "type": "lport",
                                    "value": "8028"
                                }
                            ],
                            "actions": [
                                {
                                    "portmap": true,
                                    "appPort": 80
                                }
                            ],
                            "id": 2
                        }
                    ]
                }
            ],
            "volumeRefList": [
                {
                    "uuid": "9da304b8-0135-491b-a8a4-ce59dc74526d",
                    "mount_dir": "/"
                }
            ]
        }
    ],
    "datastores": [
        {
            "id": "7e762016-3838-4129-8516-185e2fdc44cc",
            "dType": 5,
            "fqdn": "docker://index.docker.io"
        }
    ],
    "reboot": {
        "counter": 1000
    },
    "networkInstances": [
        {
            "uuidandversion": {
                "uuid": "b9f051a1-df7a-4eb8-9c70-c9452e447de1",
                "version": "1"
            },
            "displayname": "direct",
            "instType": 1,
            "activate": true,
            "port": {
                "type": 1,
                "name": "eth0"
            },
            "cfg": {},
            "ipType": 1,
            "ip": {}
        }
    ],
    "contentInfo": [
        {
            "uuid": "3d682969-9a2a-40b1-afc9-7e340a78dc1d",
            "dsId": "7e762016-3838-4129-8516-185e2fdc44cc",
            "URL": "library/nginx:latest",
            "iformat": 8,
            "displayName": "library/nginx:latest"
        }
    ],
    "volumes": [
        {
            "uuid": "9da304b8-0135-491b-a8a4-ce59dc74526d",
            "origin": {
                "type": 2,
                "downloadContentTreeID": "3d682969-9a2a-40b1-afc9-7e340a78dc1d"
            },
            "displayName": "affectionate_wiles_0_m_0"
        }
    ],
    "shutdown": {}
}```

**Comment by eriknordmark** [comment]
@FendriFiras a portmap doesn't make sense for an attachment to a switch network instance, since you have direct connectivity (no NAT). I guess EVE should check this up front just like it checks and rejects Domain Name based ACLs for switch network instance attachments.

**Comment by FendriFiras** [comment]
Yes i get it now removing the port mapping `-p 8028:80` indeed solved the problem because in Layer 2 network (Bridge) we do not port map and this is caused the error.
Thank you, @giggsoff and @eriknordmark for your help i will close the issue🙏
