### ISSUE TITLE
[pillar/nim] Rewrite queryControllerDNS to run resolver with source IP set

### ISSUE THREAD

**Issue by milan-zededa** [lf-edge/eve#3017]
Currently, `queryControllerDNS` uses `github.com/Focinfi/go-dns-resolver` which does not allow to set source IP address, meaning that DNS queries may go out through a wrong interface. This happens for example with DNS server for wwan interface. In such case DNS queries may go through one of the eth interfaces instead (and that fails as expected).

It is better to use `github.com/miekg/dns` instead, which allows to set source IP address for requests (and the repository has much more stars and activity). Here I have an example:

```
package main

import (
	"flag"
	"fmt"
	"net"
	"os"

	"github.com/miekg/dns"
)

func main() {
	domain := flag.String("domain", "zedcloud.zededa.net", "domain name")
	flag.Parse()
	fmt.Printf("domain %s\n", *domain)

	server := "8.8.8.8"

	localAddr := net.ParseIP("10.10.10.102")
	localUDPAddr := net.UDPAddr{IP: localAddr}
	d := net.Dialer{LocalAddr: &localUDPAddr}
	c := dns.Client{Dialer: &d}
	m := dns.Msg{}
	m.SetQuestion(*domain+".", dns.TypeA)
	r, _, err := c.Exchange(&m, server+":53")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if len(r.Answer) == 0 {
		fmt.Fprintln(os.Stderr, "Could not find NS records")
		os.Exit(1)
	}

	for _, ans := range r.Answer {
		if a, ok := ans.(*dns.A); ok {
			fmt.Printf("%s. %d IN A %s\n", *domain, ans.Header().Ttl, a.A.String())
		}
	}
}
```

**Comment by eriknordmark** [comment]
+1

**Comment by milan-zededa** [comment]
Done in https://github.com/lf-edge/eve/pull/3096 and https://github.com/lf-edge/eve/pull/3136
