### ISSUE TITLE
Device Identity rooted at TPM

### ISSUE THREAD

**Issue by cshari-zededa** [lf-edge/eve#40]
Moved to LF Edge/EVE Confluence space:
https://wiki.lfedge.org/display/EVE/Device+Identity+rooted+at+TPM

**Comment by rvs** [comment]
Good start @cshari-zededa  in general, but I've got a couple of quick points: in general we should start deprecating the use of /config partition. Hence I'd like to suggest you move this /config/tpm_in_use flag some other place under /persist 

Can you provide a full state transition diagram for how the TPM is being treated in these various scenarios?

Finally, I'm sure @deitch will have a lot to say on this ;-)

**Comment by cshari-zededa** [comment]
@rvs please take a look now.

**Comment by cshari-zededa** [comment]
PR #53, created for this feature implementation, has been merged. Feature documentation is at
https://wiki.lfedge.org/display/EVE/Device+Identity%2C+Onboarding%2C+Security+Foundation

Closing this issue.
