### ISSUE TITLE
commercial controller fails Device Info mesage with Bad Request: ntp sources info is nil for dev

### ISSUE THREAD

**Issue by eriknordmark** [lf-edge/eve#4003]
Please provide information requested in the template below as much as possible.

#### Describe the bug

Device running today's master not successfully send a DeviceInfo message to the commercial controller. It appears to rejected due to Bad Request: ntp sources info is nil for dev

This prevents the device state to be updated etc.

{"file":"/pillar/zedcloud/send.go:1122","func":"github.com/lf-edge/eve/pkg/pillar/zedcloud.SendOnIntf","level":"error","msg":"SendOnIntf to https://zedcloud.alpha.zededa.net/api/v2/edgedevice/id/0ba325bd-e0f8-4d90-9125-62386982a6cc/info reqlen 163 statuscode 400 Bad Request body:\n00000000  6e 74 70 20 73 6f 75 72  63 65 73 20 69 6e 66 6f  |ntp sources info|\n00000010  20 69 73 20 6e 69 6c 20  66 6f 72 20 64 65 76 20  | is nil for dev |\n00000020  30 62 61 33 32 35 62 64  2d 65 30 66 38 2d 34 64  |0ba325bd-e0f8-4d|\n00000030  39 30 2d 39 31 32 35 2d  36 32 33 38 36 39 38 32  |90-9125-62386982|\n00000040  61 36 63 63                                       |a6cc|","pid":1586,"source":"zedagent","time":"2024-06-25T22:16:33.965855682Z"}
{"file":"/pillar/zedcloud/send.go:1123","func":"github.com/lf-edge/eve/pkg/pillar/zedcloud.SendOnIntf","level":"error","msg":"Got payload for status Bad Request: ntp sources info is nil for dev 0ba325bd-e0f8-4d90-9125-62386982a6cc\n","pid":1586,"source":"zedagent","time":"2024-06-25T22:16:33.966024035Z"}
{"file":"/pillar/zedcloud/send.go:266","func":"github.com/lf-edge/eve/pkg/pillar/zedcloud.SendOnAllIntf","level":"error","msg":"All attempts to connect to zedcloud.alpha.zededa.net/api/v2/edgedevice/id/0ba325bd-e0f8-4d90-9125-62386982a6cc/info failed: send via eth0: SendOnIntf to https://zedcloud.alpha.zededa.net/api/v2/edgedevice/id/0ba325bd-e0f8-4d90-9125-62386982a6cc/info reqlen 163 statuscode 400 Bad Request body:\n00000000  6e 74 70 20 73 6f 75 72  63 65 73 20 69 6e 66 6f  |ntp sources info|\n00000010  20 69 73 20 6e 69 6c 20  66 6f 72 20 64 65 76 20  | is nil for dev |\n00000020  30 62 61 33 32 35 62 64  2d 65 30 66 38 2d 34 64  |0ba325bd-e0f8-4d|\n00000030  39 30 2d 39 31 32 35 2d  36 32 33 38 36 39 38 32  |90-9125-62386982|\n00000040  61 36 63 63                                       |a6cc|","pid":1586,"source":"zedagent","time":"2024-06-25T22:16:33.966127362Z"}

#### Recent release

Is it reproducible on a recent release? (See the [list of releases](https://github.com/lf-edge/eve/releases))

#### Duplicate

If you are reporting a new issue, make sure that we do not have any duplicates
already open. You can ensure this by searching the issue list for this
repository. If there is a duplicate, please close your issue and add a comment
pointing to the existing issue instead.

#### How to reproduce

Include a list of steps showing how to reproduce the bug. Also include:

* EVE-OS version [e.g., 6.6.3]
* EVE-OS hardware architecture [e.g., arm64, amd64]

#### Additional context

Add any other information about the problem here.

**Comment by eriknordmark** [comment]
Not clear to me whether the commercial controller needs to be fixed to accept the empty list.
If not, this makes EVE be able to successfully send Device Info messages to the commercial controller:
```
diff --git a/pkg/pillar/cmd/zedagent/handlentp.go b/pkg/pillar/cmd/zedagent/handlentp.go
index bef483924..df3b9798b 100644
--- a/pkg/pillar/cmd/zedagent/handlentp.go
+++ b/pkg/pillar/cmd/zedagent/handlentp.go
@@ -130,6 +130,11 @@ func publishNTPSourcesToDest(ctx *zedagentContext,
                // so just return
                return
        }
+       if len(infoNTPSources.Sources) == 0 {
+               log.Noticef("XXX no NTP sources")
+               // XXX controller will reject
+               return
+       }
        infoMsg := &info.ZInfoMsg{
                Ztype: info.ZInfoTypes_ZiNTPSources,
                DevId: devUUID.String(),
```

**Comment by rouming** [comment]
Fixed on the controller side.
