### ISSUE TITLE
Unable to build kernel package in eve-8.12.0-lts

### ISSUE THREAD

**Issue by geoffreymoyerweatherford** [lf-edge/eve#4268]
#### Describe the bug

Kernel package fails to build with a make pkg/kernel command. The failure is specific to the following line M=/tmp/xr_usb_serial_common_lnx-3.6-and-newer-pak in the pkg/kernel Dockerfile. 

Changing line from **M=/tmp/xr_usb_serial_common_lnx-3.6-and-newer-pak** to **M=/tmp/xr/Linux_3.6** fixed the issue. 

#### Recent release

Is it reproducible on a recent release? Not that I am aware of. Only reproduced on eve-8.12.0-lts and 8.11.0

#### How to reproduce

Run a 'make pkg/kernel' on tags eve-8.12.0-lts, 8.11.0, or any others that have same pkg/kernel Dockerfile as these.

#### Expected behavior

Will fail on [kernel-build 16/22] 

#### Error message

 => [kernel-build 16/22] RUN unzip -d /tmp /tmp/xr.zip ;    make -C /linux INSTALL_MOD_PATH=/tmp/kernel-modules                    M=/tmp/xr_usb_serial_common_lnx-3.6-and-newer-pak          modules modules_inst  0.5s
 => => #   inflating: Linux_3.6/README.txt
 => => #   inflating: Linux_3.6/xr_usb_serial_common.c
 => => #   inflating: Linux_3.6/xr_usb_serial_common.h
 => => #   inflating: Linux_3.6/xr_usb_serial_hal.c
 => => #   inflating: Linux_3.6/xr_usb_serial_ioctl.h
 => => # make: Entering directory '/linux'
Error building "lfedge/eve-kernel:4ed7425f92b01a9fbbc83ebd23704dac4bd38631-dirty-8e4a914": error building for arch amd64: failed to solve: process "/bin/sh -c export KERNEL_SERIES=$(eval echo \\$KERNEL_VERSION_$(uname -m) | sed -e 's#.[^.]*$#.x#') ; /bin/sh -c \"$1\" - unzip -d /tmp /tmp/xr.zip ;    make -C /linux INSTALL_MOD_PATH=/tmp/kernel-modules                    M=/tmp/xr_usb_serial_common_lnx-3.6-and-newer-pak          modules modules_install" did not complete successfully: exit code: 2
make: *** [Makefile:762: eve-kernel] Error 1

**Comment by rene** [comment]
@geoffreymoyerweatherford , thanks for reporting this issue.... is there any particular reason on why are you using this old EVE-OS version? If there isn't any particular reason, I strongly suggest you to try a recent LTS version, like 12.0.3-lts or any newer from stable branches.... as you mentioned in the ticket, this issue doesn't happen on our recent versions.

**Comment by geoffreymoyerweatherford** [comment]
@rene thanks for the reply. I am using this particular version due to direction given from management. I can use your reply as an argument to push to upgrade to a more stable version.

**Comment by rene** [comment]
Ok, definitely there are a lot of improvements and even API additions (more config. options, etc) in our recent versions. I will close this issue as won't fix since we don't support version 8 anymore.
