### ISSUE TITLE
Problems with 'make yetus'

### ISSUE THREAD

**Issue by sadov** [lf-edge/eve#480]
# Description

Finished with errors. 

# Steps to Reproduce

Run 'make yetus'

# Actual Results
```
Running yetus
build-tools/src/yetus/test-patch.sh
ERROR: yetus-dl: unable to fetch https://www.apache.org/dyn/closer.cgi?action=download&filename=yetus/0.11.0/apache-yetus-0.11.0-bin.tar.gz.asc
build-tools/src/yetus/test-patch.sh: line 56: /tmp/yetus/bin/test-patch: No such file or directory
Makefile:157: recipe for target 'yetus' failed
make: *** [yetus] Error 127
eve_make_yetus.002.log (END)
```
# Expected Results
```
Running yetus
build-tools/src/yetus/test-patch.sh
/tmp/yetus-out has been created
Modes: Docker
....
============================================================================
============================================================================
                              Finished build.
============================================================================
============================================================================
```
# Additional Information

The root of the problem is in the apache/yetus version, which fixed on [pull request](https://github.com/lf-edge/eve/pull/477).

**Comment by rvs** [comment]
Hey @sadov -- thanks for reporting this -- much appreciated! I see that you already submitted a PR #477 which is even better ;-)

Btw, in general, if you have plans to submit a PR -- there's typically no need to open a separate issue (no danger either - basically up to you)
