### ISSUE TITLE
make run does not work on Ubuntu 16.04

### ISSUE THREAD

**Issue by salerio-gs** [lf-edge/eve#61]
**Description**

After building cleanly on Ubuntu 16.04 and attempt to make run fails with an error (qemu-system-x86_64: -nic: invalid option).

**Steps to reproduce the issue:**

make build-tools
make live
make run

**Describe the results you received:**

```
Creating go builder image for user peter
eve-build-peter docker container is ready to use
cd /build1/peter/EVE/eve/dist/amd64/bios ; _() { C=`docker create $1 fake` ; docker export $C | tar -xf - $2 ; docker rm $C ; } ; _ lfedge/eve-uefi:aef36d9c29fd16f9bae72a74d887568f0ef138f0-amd64 OVMF.fd
9d8e7a50bb12765847ff7b4799f6ac4bc6828d0f0e50a962cfe97983b3039f0c
qemu-system-x86_64 -smbios type=1,serial=31415926 -m 4096 -smp 4 -display none -serial mon:stdio -bios /build1/peter/EVE/eve/dist/amd64/bios/OVMF.fd -rtc base=utc,clock=rt -nic user,id=eth0,net=192.168.1.0/24,dhcpstart=192.168.1.10,hostfwd=tcp::2222-:22 -nic user,id=eth1,net=192.168.2.0/24,dhcpstart=192.168.2.10 -cpu SandyBridge -drive file=/build1/peter/EVE/eve/dist/amd64/live.img,format=qcow2
qemu-system-x86_64: -nic: invalid option
Makefile:152: recipe for target 'run' failed
make: *** [run] Error 1
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

qemu-system-x86_64 is at version 2.5.0

**Comment by rvs** [comment]
Hey @salerio-gs -- thanks for reporting this. Looks like we've been too eager to assume qemu 3.x.y. I've submitted PR #69 to make sure it can run with older qemu (but honestly I'm not sure what else may be the problem if it runs -- we've been testing with qemu 3.x.y).

Still once #69 lands -- it would be great if you could try it on your system and let us know

**Comment by salerio-gs** [comment]
@rvs Sure I will do that...

**Comment by eriknordmark** [comment]
I've tried this on Ubuntu 18.04 and it works (didn't use to work before the fix)

**Comment by rvs** [comment]
Hey @salerio-gs any chance you can let us know if we can close this?

**Comment by salerio-gs** [comment]
@rvs all is well, can be closed.
