### ISSUE TITLE
musl is an undocumented host requirement on Ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by rcwoolley** [lf-edge/eve#622]
The "make live" step in the documentation will fail to execute linuxkit on Ubuntu 18.04.3 LTS.

If you attempt to execute it, bash will complain:

```
$ ./build-tools/bin/linuxkit
-bash: ./build-tools/bin/linuxkit: No such file or directory

```
Because it can't find the shared libraries:

```
$ ldd ./build-tools/bin/linuxkit
        linux-vdso.so.1 (0x00007fff1e98e000)
        libc.musl-x86_64.so.1 => not found

```
This can be resolved by installing the "musl" package.

`sudo apt install musl
`
```
$ ./build-tools/bin/linuxkit
Please specify a command.

USAGE: linuxkit [options] COMMAND

Commands:
  build       Build an image from a YAML file
  metadata    Metadata utilities
  pkg         Package building
  push        Push a VM image to a cloud or image store
  run         Run a VM image on a local hypervisor or remote cloud
  serve       Run a local http server (for iPXE booting)
  version     Print version information
  help        Print this message

Run 'linuxkit COMMAND --help' for more information on the command

Options:
  -q    Quiet execution
  -v    Verbose execution


```

I suggest adding documentation listing musl as a necessary host requirement.

**Comment by kgiori** [comment]
Hi @rcwoolley -- looks like this was never resolved/responded to. Is this still an issue that requires better documentation? And if so, any suggestions on the best place to highlight the need?

**Comment by rcwoolley** [comment]
Thanks for following up.   I haven't tested this since February 2020.
However, if it is still a problem, but I would suggest adding "musl" to the
list of packages to apt-get install in the README.md file:
On Ubuntu Linux

$ sudo apt-get install -y git make jq qemu binfmt-support qemu-user-static \
    qemu-utils qemu-system-x86 qemu-system-aarch64

**Comment by rene** [comment]
This issue is deprecated. I've tested EVE (master) on Ubuntu 18.04 and the issue is not reproducible anymore.
