### ISSUE TITLE
api/API.md is outdated

### ISSUE THREAD

**Issue by bharani-zededa** [lf-edge/eve#64]
**Description**

api/API.md is outdated. It has not been updated with the new api proto directory layout (organized based on the REST APIs). Some APIs are not documented.

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by deitch** [comment]
Indeed. Care to open a PR for it?

In the future, we probably should update the docs on the API directions, then change layout and code. It would be good to make the doc the official API definition.

**Comment by bharani-zededa** [comment]
Ack.

**Comment by eriknordmark** [comment]
This was addressed in a recent PR
