### ISSUE TITLE
Unable to cross-compile pillar for arm64

### ISSUE THREAD

**Issue by deitch** [lf-edge/eve#8]
**Description**

Unable to cross-compile pillar for arm64

**Steps to reproduce the issue:**

```
cd pkg/pillar
make zedbox ARCH=arm64
```

**Describe the results you received:**

```
$ make zedbox ARCH=arm64
mkdir -p dist/arm64
Creating go builder image for user adeitcher
Building dist/arm64/zedbox
# runtime/cgo
gcc_arm64.S: Assembler messages:
gcc_arm64.S:27: Error: no such instruction: `stp x19,x20,[sp,'
gcc_arm64.S:28: Error: no such instruction: `stp x21,x22,[sp,'
gcc_arm64.S:29: Error: no such instruction: `stp x23,x24,[sp,'
gcc_arm64.S:30: Error: no such instruction: `stp x25,x26,[sp,'
gcc_arm64.S:31: Error: no such instruction: `stp x27,x28,[sp,'
gcc_arm64.S:32: Error: no such instruction: `stp x29,x30,[sp,'
gcc_arm64.S:33: Error: too many memory references for `mov'
gcc_arm64.S:35: Error: too many memory references for `mov'
gcc_arm64.S:36: Error: too many memory references for `mov'
gcc_arm64.S:37: Error: too many memory references for `mov'
gcc_arm64.S:39: Error: no such instruction: `blr x20'
gcc_arm64.S:40: Error: no such instruction: `blr x19'
gcc_arm64.S:42: Error: no such instruction: `ldp x29,x30,[sp],'
gcc_arm64.S:43: Error: no such instruction: `ldp x27,x28,[sp],'
gcc_arm64.S:44: Error: no such instruction: `ldp x25,x26,[sp],'
gcc_arm64.S:45: Error: no such instruction: `ldp x23,x24,[sp],'
gcc_arm64.S:46: Error: no such instruction: `ldp x21,x22,[sp],'
gcc_arm64.S:47: Error: no such instruction: `ldp x19,x20,[sp],'
make: *** [dist/arm64/zedbox] Error 2
```

**Describe the results you expected:**

It should build

**Comment by vielmetti** [comment]
@deitch the README instructions refer to a ZARCH=arm64 (instead of ARCH=arm64) - can you try with that?

**Comment by deitch** [comment]
@vielmetti , it actually isn't the entire thing, just the `pkg/pillar`, and specifically the binary. I should have labeled the issue better, but I had ported it over from other repos.

I will update the description.

**Comment by rvs** [comment]
@vielmetti great to see you around! btw, at Linux Foundation level we're talking about getting some ARM infrastructure for build servers. Anything you guys can help with?

**Comment by vielmetti** [comment]
@rvs Happy to help, probably the best way is via email to start (ed@packet.com). We currently provide a cluster through the CNCF right now, as well as Arm infrastructure for CI sponsored directly by Arm. A couple possible ways to proceed depending mostly on scale and setup needs.

**Comment by rouming** [comment]
@eriknordmark Can be closed, implemented here https://github.com/lf-edge/eve/pull/2998
