### ISSUE TITLE
Merging of image yml files

### ISSUE THREAD

**Issue by deitch** [lf-edge/eve#860]
This is a discussion issue to figure out how we handle multiple image yml files. As of this writing, and the recently merged #849, we have multiple rootfs image files:

1. A core `rootfs.yml` which contains all of the common information for images
1. A patch file per unique build, e.g. Xen or KVM or RPi

Actually, each is a `.yml.in` which then is merged and patched, but getting past `.in` files is a separate discussion.

The problem with using patch files in this use case is that they are brittle. They have very specific lines that you add/remove/change. This works well for source code, where lines have little inherent structure. yml (and json) are by definition structured and easy to patch. There even are RFC standards for [json patch](http://tools.ietf.org/html/rfc6902) and [json merge patch](https://tools.ietf.org/html/rfc7386).

The kubernetes version of strategic merge patch is even easier, but depends on some annotations.

A JSON Patch to replace [rootfs-acrn.yml.in](https://github.com/lf-edge/eve/blob/master/images/rootfs-acrn.yml.in.patch) would look something like:

```
```

**Comment by rene** [comment]
Closing since was solved by PR https://github.com/lf-edge/eve/pull/3692 .
