### ISSUE TITLE
make run pulls in ../adam/run if it exists, breaking things

### ISSUE THREAD

**Issue by deitch** [lf-edge/eve#948]
# Description

The Makefile [here](https://github.com/lf-edge/eve/blob/master/Makefile#L97) sets:

```makefile
CONF_PART=$(CURDIR)/../adam/run/config
```

and then includes it [here](https://github.com/lf-edge/eve/blob/master/Makefile#L140) as:

```makefile
QEMU_OPTS_CONF_PART=$(shell [ -d $(CONF_PART) ] && echo '-drive file=fat:rw:$(CONF_PART),format=raw')
```

This means that if someone has the adam repo in the right place, whatever they are using will show up rather suddenly. This sucks the default runtime config for adam as a standalone into a running eve. 

This should just be removed

cc @rvs 

# Steps to Reproduce

1. Run adam in its usual place
1. Run eve
1. See that the config is loaded from there

**Comment by rvs** [comment]
This is such a 🤦 -- and yes -- I'm burning it with 🔥 now @deitch
